# Generated by Django 3.0.4 on 2020-03-17 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.IntegerField(db_index=True, primary_key=True, serialize=False, verbose_name='Id')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('last_name', models.CharField(max_length=64, verbose_name='Last_Name')),
                ('sex', models.IntegerField(choices=[(1, 'Male'), (2, 'Famale'), (0, 'Undefined')], verbose_name='Customer_Sex')),
                ('type', models.IntegerField(choices=[(1, 'Vendor'), (2, 'Customer'), (0, 'Undefined')], verbose_name='Clients_Type')),
            ],
        ),
        migrations.CreateModel(
            name='Poi',
            fields=[
                ('poi_id', models.IntegerField(db_index=True, primary_key=True, serialize=False, verbose_name='POI_Id')),
                ('net_number', models.IntegerField(db_index=True, verbose_name='Net_Number')),
            ],
        ),
        migrations.CreateModel(
            name='Stores',
            fields=[
                ('store_id', models.IntegerField(db_index=True, primary_key=True, serialize=False, verbose_name='Store_Id')),
                ('store_name', models.CharField(max_length=64, verbose_name='Store_Name')),
                ('store_description', models.CharField(max_length=64, verbose_name='Store_Description')),
                ('store_type', models.IntegerField(choices=[(1, 'DutyFree'), (2, 'WithVat'), (0, 'Undefined')], verbose_name='Store_Type')),
            ],
        ),
    ]
