# Generated by Django 3.0.4 on 2020-03-17 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='id',
            field=models.IntegerField(db_index=True, primary_key=True, serialize=False, unique=True, verbose_name='Id'),
        ),
        migrations.AlterField(
            model_name='poi',
            name='net_number',
            field=models.IntegerField(db_index=True, unique=True, verbose_name='Net_Number'),
        ),
        migrations.AlterField(
            model_name='poi',
            name='poi_id',
            field=models.IntegerField(db_index=True, primary_key=True, serialize=False, unique=True, verbose_name='POI_Id'),
        ),
        migrations.AlterField(
            model_name='stores',
            name='store_id',
            field=models.IntegerField(db_index=True, primary_key=True, serialize=False, unique=True, verbose_name='Store_Id'),
        ),
    ]
