# Generated by Django 3.0.4 on 2020-03-18 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20200317_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poi',
            name='net_number',
            field=models.IntegerField(db_index=True, verbose_name='Net_Number'),
        ),
    ]
