# Generated by Django 3.0.4 on 2020-03-18 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_auto_20200318_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='poi',
            name='store_number',
            field=models.IntegerField(db_index=True, default=-1, verbose_name='Store_Number'),
            preserve_default=False,
        ),
    ]
