# Generated by Django 3.0.4 on 2020-03-30 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_binaries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binaries',
            name='binary_file',
            field=models.BinaryField(),
        ),
    ]
