# Generated by Django 3.0.4 on 2020-03-30 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_remove_binaries_remark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='binaries',
            name='timestamp',
        ),
    ]
