# Generated by Django 3.0.4 on 2020-03-30 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_auto_20200330_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='binaries',
            name='remark',
        ),
    ]
